# AppFlowy Cloud - Full deployment with system PostgreSQL and MinIO

services:
  nginx:
    restart: on-failure
    image: nginx
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/certificate.crt:/etc/nginx/ssl/certificate.crt
      - ./nginx/ssl/private_key.key:/etc/nginx/ssl/private_key.key
    depends_on:
      - gotrue
      - appflowy_cloud
      - admin_frontend

  redis:
    restart: on-failure
    image: redis

  gotrue:
    restart: on-failure
    build:
      context: docker/gotrue
      dockerfile: Dockerfile
    image: appflowyinc/gotrue:latest
    environment:
      - GOTRUE_ADMIN_EMAIL=${GOTRUE_ADMIN_EMAIL:-admin@xiaomabiji.com}
      - GOTRUE_ADMIN_PASSWORD=${GOTRUE_ADMIN_PASSWORD:-admin123}
      - GOTRUE_DISABLE_SIGNUP=false
      - GOTRUE_SITE_URL=appflowy-flutter://
      - GOTRUE_URI_ALLOW_LIST=**
      - GOTRUE_JWT_SECRET=${GOTRUE_JWT_SECRET:-your-super-secret-jwt-token-with-at-least-32-characters-long}
      - GOTRUE_JWT_EXP=3600
      - GOTRUE_JWT_ADMIN_GROUP_NAME=supabase_admin
      - GOTRUE_DB_DRIVER=postgres
      - API_EXTERNAL_URL=${API_EXTERNAL_URL:-https://api.xiaomabiji.com}
      - DATABASE_URL=${GOTRUE_DATABASE_URL:-postgres://postgres:password@postgres:5432/postgres}
      - PORT=9999
      - GOTRUE_MAILER_AUTOCONFIRM=true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  appflowy_cloud:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    image: appflowyinc/appflowy_cloud:latest
    environment:
      - RUST_LOG=info
      - APPFLOWY_ENVIRONMENT=production
      - APPFLOWY_DATABASE_URL=${APPFLOWY_DATABASE_URL:-postgres://postgres:password@postgres:5432/postgres}
      - APPFLOWY_REDIS_URI=${APPFLOWY_REDIS_URI:-redis://redis:6379}
      - APPFLOWY_GOTRUE_JWT_SECRET=${GOTRUE_JWT_SECRET:-your-super-secret-jwt-token-with-at-least-32-characters-long}
      - APPFLOWY_GOTRUE_JWT_EXP=3600
      - APPFLOWY_GOTRUE_BASE_URL=${APPFLOWY_GOTRUE_BASE_URL:-http://gotrue:9999}
      - APPFLOWY_S3_CREATE_BUCKET=true
      - APPFLOWY_S3_USE_MINIO=true
      - APPFLOWY_S3_MINIO_URL=${APPFLOWY_S3_MINIO_URL:-http://host.docker.internal:9000}
      - APPFLOWY_S3_ACCESS_KEY=${APPFLOWY_S3_ACCESS_KEY:-minioadmin}
      - APPFLOWY_S3_SECRET_KEY=${APPFLOWY_S3_SECRET_KEY:-minioadmin}
      - APPFLOWY_S3_BUCKET=${APPFLOWY_S3_BUCKET:-appflowy}
      - APPFLOWY_ACCESS_CONTROL=false
      - APPFLOWY_DATABASE_MAX_CONNECTIONS=10
      - APPFLOWY_WEB_URL=${APPFLOWY_WEB_URL:-https://xiaomabiji.com}
    depends_on:
      - gotrue
    ports:
      - "8005:8000"

    extra_hosts:
      - "host.docker.internal:host-gateway"

  admin_frontend:
    restart: on-failure
    build:
      context: .
      dockerfile: ./admin_frontend/Dockerfile
    image: appflowyinc/admin_frontend:latest
    environment:
      - RUST_LOG=info
      - ADMIN_FRONTEND_REDIS_URL=redis://redis:6379
      - ADMIN_FRONTEND_GOTRUE_URL=http://gotrue:9999
      - ADMIN_FRONTEND_APPFLOWY_CLOUD_URL=http://appflowy_cloud:8000
      - ADMIN_FRONTEND_PATH_PREFIX=
    ports:
      - "3005:3000"
    depends_on:
      - gotrue
      - appflowy_cloud

  appflowy_worker:
    restart: on-failure
    build:
      context: .
      dockerfile: ./services/appflowy-worker/Dockerfile
    image: appflowyinc/appflowy_worker:latest
    environment:
      - RUST_LOG=info
      - APPFLOWY_ENVIRONMENT=production
      - APPFLOWY_WORKER_REDIS_URL=redis://redis:6379
      - APPFLOWY_WORKER_ENVIRONMENT=production
      - APPFLOWY_WORKER_DATABASE_URL=${APPFLOWY_WORKER_DATABASE_URL:-postgres://postgres:password@postgres:5432/postgres}
      - APPFLOWY_WORKER_DATABASE_NAME=postgres
      - APPFLOWY_WORKER_IMPORT_TICK_INTERVAL=30
      - APPFLOWY_S3_USE_MINIO=true
      - APPFLOWY_S3_MINIO_URL=http://host.docker.internal:9000
      - APPFLOWY_S3_ACCESS_KEY=minioadmin
      - APPFLOWY_S3_SECRET_KEY=minioadmin
      - APPFLOWY_S3_BUCKET=appflowy
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway" 
