[package]
name = "admin_frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
axum = {version = "0.6.20", features = ["json"]}
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros"] }
askama = "0.12.1"
axum-extra = { version = "0.8.0", features = ["cookie"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"

# local dependencies
gotrue = { path = "../libs/gotrue" }
gotrue-entity = { path = "../libs/gotrue-entity" }
dotenv = "0.15.0"
reqwest = "0.11.22"
tower-service = "0.3.2"
