name: Deployment AppFlowy Cloud and Admin Frontend for Kube Environment
on:
  push:
    branches:
     - 'main'
     - 'test_deploy_*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build docker images
        run: |
          docker compose build appflowy_cloud admin_frontend
          docker images
      - name: push docker images to docker hub
        run: |
          docker images
          docker tag appflowy-cloud-appflowy_cloud appflowyinc/appflowy_cloud:dev
          docker tag appflowy-cloud-admin_frontend appflowyinc/appflowy_cloud:dev
          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login --username appflowyinc --password-stdin
          docker push appflowyinc/appflowy_cloud:dev
          docker push appflowyinc/admin_frontend:dev
